---

- name: send keys directory to {{ ovpn_dir }}
  become: true
  synchronize:
    mode: push
    src: "{{ ovpn_base }}/keys"
    dest: "{{ ovpn_dir }}"

- name: Ensure proper permissions
  become: true
  file:
    path: "{{ ovpn_keys_dir }}"
    state: directory
    owner: root
    group: root
    mode: "o-rx"
    recurse: true

- name: restart openvpn service
  become: true
  service: name=openvpn state=restarted
