---
- name: Install the packages
  apt:
    name: ["openvpn"]
    state: present
    update_cache: yes
  become: true

- name: Basic Facts
  set_fact:
    cert_filename: "{{ fqdn }}.ovpn"
    client_file: "/etc/openvpn/{{ fqdn }}.conf"

- name: copy certificate file to target
  become: true
  copy:
    src: "{{ local_ovpn_base }}/certs/{{ cert_filename }}"
    dest: "{{ client_file }}"
    owner: root
    group: root
    mode: 0755

- name: Set OpenVPN client to start on reboot
  become: true
  lineinfile:
    dest: "/etc/default/openvpn"
    regexp: "{{ item.needle }}"
    line: "{{ item.line }}"
  with_items:
    - { needle: '#AUTOSTART="all"', line: 'AUTOSTART="all"' }

- name: Restart the instance
  include_role:
    name: isaackehle.restart
