---


- name: Install the packages
  apt:
    name: ['openvpn']
    state: present
    update_cache: yes
  become: true

- set_fact:
    cert_filename:  "{{ server_fqdn }}.ovpn"
    client_file:    "/etc/openvpn/{{ server_fqdn }}.conf"

- name: copy certificate file to target
  become: true
  copy:
    src: "{{ ovpn_base }}/certs/{{ cert_filename }}"
    dest: "{{ client_file }}"
    owner: root
    group: root
    mode: 0755

- name: Set OpenVPN client to start on reboot
  become: true
  lineinfile: dest="/etc/default/openvpn" regexp={{ item.needle }} line={{ item.line }}
  with_items:
    - { needle: '#AUTOSTART="all"', line: 'AUTOSTART="all"' }

- name: restart the VM
  include_role:
    name: pgkehle.restart
