---

- fail: msg="Please ensure '{{ item }}' is set"
  when:
    - not {{ item }} is defined or {{ item }} == ""
  with_items:
    - target_host

- set_fact:
    target_vars:    "{{ hostvars[target_host] }}"

- set_fact:
    target_fqdn:    "{{ target_vars.server_fqdn }}"
  when: target_host != 'localhost'

- shell: hostname
  connection: local
  register: host_long
  when: target_host == 'localhost'

- set_fact:
    target_fqdn:    "{{host_long.stdout}}"
  when: target_host == 'localhost'

- set_fact:
    cert_filename:  "{{ target_fqdn }}.ovpn"

- name: Check to see if file exists
  connection: local
  stat: path="{{ ovpn_base }}/certs/{{ cert_filename }}"
  register: cert_stat

- debug: var=cert_stat

- set_fact:
    need_generate: "{{not cert_stat.stat.exists|bool}}"

#- debug: var=need_generate

- include: easy-ovpn-init.yml
  when: need_generate|bool == true

- name: push client key script
  template: src=../templates/client_gen.sh.j2 dest="/tmp/client_gen.sh"
  become: false
  when: need_generate|bool == true

- name: run the client key script
  command: bash /tmp/client_gen.sh
  when: need_generate|bool == true

- name: push client generation script
  template: src=../templates/client_build_cert.sh.j2 dest="/tmp/client_build_cert.sh"
  become: false
  when: need_generate|bool == true

- name: run the client generation script
  command: bash /tmp/client_build_cert.sh
  when: need_generate|bool == true

- name: Ensure local private certs directory exists
  local_action: file path="{{ ovpn_base }}/certs" state=directory
  when: need_generate|bool == true

- name: copy certificate file to local
  become: true
  fetch: src="{{ easy_ovpn_certs }}/{{ cert_filename }}" dest="{{ ovpn_base }}/certs/{{ cert_filename }}" flat=true
  when: need_generate|bool == true

- name: copy updated keys directory to local
  become: true
  when: need_generate|bool == true
  synchronize:
    mode: pull
    src: "{{ easy_ovpn_keys }}"
    dest: "{{ ovpn_base }}"

- name: Kill old easy_ovpn directory
  file: path="{{ easy_ovpn_dir }}" state=absent
  become: false
