---

- name: Kill old easy_ovpn directory
  file: path="{{ easy_ovpn_dir }}" state=absent
  become: false

- name: Create the easy_ovpn directory
  command: make-cadir "{{ easy_ovpn_dir }}"
  become: false

- name: Change Key Data
  lineinfile: dest="{{ easy_ovpn_vars }}" regexp={{ item.needle }} line={{ item.line }}
  become: false
  with_items:
    - { needle: 'KEY_COUNTRY', line: 'export KEY_COUNTRY="{{sc_country}}"' }
    - { needle: 'KEY_PROVINCE', line: 'export KEY_PROVINCE="{{sc_state}}"' }
    - { needle: 'KEY_CITY', line: 'export KEY_CITY="{{sc_locality}}"' }
    - { needle: 'KEY_ORG', line: 'export KEY_ORG="{{sc_organization}}"' }
    - { needle: 'KEY_OU', line: 'export KEY_OU="{{sc_ou}}"' }
    - { needle: 'KEY_EMAIL', line: 'export KEY_EMAIL="{{sc_email}}"' }
    - { needle: 'KEY_NAME', line: 'export KEY_NAME="{{sc_domain_comp}}"' }

- name: Create {{ easy_ovpn_certs }}
  file: path="{{ easy_ovpn_certs }}" state=directory
  become: false

#- name: Copy current keys to easy openvpn directory
#  synchronize:
#    src: "{{ ovpn_keys_dir }}"
#    dest: "{{ easy_ovpn_dir }}"
#  delegate_to: "{{ inventory_hostname }}"

- name: push the keys directory to {{ easy_ovpn_dir }}
  become: false
  synchronize:
    mode: push
    src: "{{ ovpn_base }}/keys"
    dest: "{{ easy_ovpn_dir }}"

- name: push config template
  template: src=../templates/client.conf.j2 dest="{{ easy_ovpn_dir }}/client.conf"
  become: false

