---

- fail: msg="Please ensure '{{ item.use }}' is set"
  when:
    - not item is defined or not item.tst is defined or item.tst == ""
  with_items:
    - {tst: vpn_server_group_name, use: 'Ansible Group Name of portal servers'}
    - {tst: target_servers, use: 'List of servers to be added to OpenVPN portal list'}
  tags:
    - all

- include_tasks: ./server-init.yml
  when: ((['server_init'] | intersect(flags)) | length > 0)
  tags: ['server_init']

- include_tasks: ./server-config.yml
  when: ((['server_config'] | intersect(flags)) | length > 0)
  tags: ['server_config']

- include_tasks: ./server-cert-generate.yml
  when: ((['server_cert_gen'] | intersect(flags)) | length > 0)
  tags: ['server_cert_gen']

- include_tasks: ./server-cert-pull.yml
  when: ((['server_cert_pull'] | intersect(flags)) | length > 0)
  tags: ['server_cert_pull']

- include_tasks: ./easy-ovpn-init.yml
  when: ((['easy_ovpn_init'] | intersect(flags)) | length > 0)
  tags: ['easy_ovpn_init']

- include_tasks: ./client-cert-generate.yml
  when: ((['client_cert_gen'] | intersect(flags)) | length > 0)
  tags: ['client_cert_gen']

- include_tasks: ./client-cert-sync.yml
  when: ((['client_cert_sync'] | intersect(flags)) | length > 0)
  tags: ['client_cert_sync']

- include_tasks: ./easy-ovpn-kill.yml
  when: ((['easy_ovpn_kill'] | intersect(flags)) | length > 0)
  tags: ['easy_ovpn_kill']

- include_tasks: ./client-deploy.yml
  when: ((['client_deploy'] | intersect(flags)) | length > 0)
  tags: ['client_deploy']
