---

- fail: msg="Please ensure '{{ item.use }}' is set"
  when:
    - not {{ item.tst }} is defined or {{ item.tst }} == ""
  with_items:
    - {tst: group_name, use: 'Ansible Group Name of portal servers'}
    - {tst: target_servers, use: 'List of servers to be added to OpenVPN portal list'}
  tags:
    - init
    - config
    - generate
    - pull
    - sync
    - deploy
    - kill

- include: ./server-init.yml
  when: do_server_init|bool == true
  tags:
    - init

- include: ./server-config.yml
  when: do_server_config|bool == true
  tags:
    - config

- include: ./server-cert-generate.yml
  when: do_server_cert_gen|bool == true
  tags:
    - generate

- include: ./server-cert-pull.yml
  when: do_server_cert_pull|bool == true
  tags:
    - pull

- include: ./easy-ovpn-init.yml
  when: do_easy_ovpn_init|bool == true
  tags:
    - init

- include: ./client-cert-generate.yml
  when: do_client_cert_gen|bool == true
  tags:
    - generate

- include: ./client-cert-sync.yml
  when: do_client_cert_sync|bool == true
  tags:
    - sync

- include: ./easy-ovpn-kill.yml
  when: do_easy_ovpn_kill|bool == true
  tags:
    - kill

- include: ./client-deploy.yml
  when: do_client_deploy|bool == true
  tags:
    - deploy
