---

- include: ./server-init.yml
  when: server_init|bool == true

- include: ./server-config.yml
  when: server_config|bool == true

- include: ./easy-ovpn-init.yml
  when: easy_ovpn_init|bool == true

- include: ./server-cert-generate.yml
  when: server_cert_gen|bool == true

- include: ./server-cert-pull.yml
  when: server_cert_pull|bool == true

- include: ./client-cert-generate.yml
  when: client_cert_gen|bool == true

- include: ./client-cert-sync.yml
  when: client_cert_sync|bool == true

- include: ./client-deploy.yml
  when: client_deploy|bool == true
  tags:
    - deploy
