---

- fail: msg="Please ensure '{{ item.use }}' is set"
  when:
    - not {{ item.tst }} is defined or {{ item.tst }} == ""
  with_items:
    - {tst: group_name, use: 'Ansible Group Name of portal servers'}
    - {tst: target_servers, use: 'List of servers to be added to OpenVPN portal list'}
  tags:
    - init
    - config
    - generate
    - pull
    - sync
    - deploy
    - kill

- include: ./server-init.yml
  tags: ['server_init']

- include: ./server-config.yml
  tags: ['server_config']

- include: ./server-cert-generate.yml
  tags: ['server_cert_gen']

- include: ./server-cert-pull.yml
  tags: ['server_cert_pull']

- include: ./easy-ovpn-init.yml
  tags: ['easy_ovpn_init']

- include: ./client-cert-generate.yml
  tags: ['client_cert_gen']

- include: ./client-cert-sync.yml
  tags: ['client_cert_sync']

- include: ./easy-ovpn-kill.yml
  tags: ['easy_ovpn_kill']

- include: ./client-deploy.yml
  tags: ['client_deploy']
