---

- name: Push server configuration file
  template: src=../templates/server.conf.j2 dest="{{ovpn_server_cfg_file}}" owner=root group=root mode="0755"
  become: true




#fpath="/etc/openvpn"
#files=( "server.conf" "ca.crt" "dh2048.pem" "server.crt" "server.key" "ipp.txt" )
#
#for fname in "${files[@]}"
#do
#  sudo scp -i ${CUST_PEMFILE} -o "StrictHostKeyChecking=no" $fpath/$fname ${CUST_USR}@${targetIp}:/tmp/$fname
#  ssh -i ${CUST_PEMFILE} -o "StrictHostKeyChecking=no" ${CUST_USR}@${targetIp} -t "
#  sudo sh -c 'cat /tmp/$fname > $fpath/$fname'
#  rm /tmp/$fname"
#done
#
#fpath="~/openvpn-ca"
#files=( "vars" )
#
#for fname in "${files[@]}"
#do
#  sudo scp -i ${CUST_PEMFILE} -o "StrictHostKeyChecking=no" $fpath/$fname ${CUST_USR}@${targetIp}:/tmp/$fname
#  ssh -i ${CUST_PEMFILE} -o "StrictHostKeyChecking=no" ${CUST_USR}@${targetIp} -t "
#  sudo sh -c 'cat /tmp/$fname > $fpath/$fname'
#  rm /tmp/$fname"
#done
#
#spath="~/openvpn-ca/keys"
#tpath="~/openvpn-ca"
#tmppath="/tmp/keys"
#sudo rm -rf $spath/*.old
#sudo rm -rf $spath/*.ovpn
#sudo rsync -e "ssh -i ${CUST_PEMFILE} -o 'StrictHostKeyChecking=no'" -av $spath ${CUST_USR}@${targetIp}:/tmp
#
#ssh -i ${CUST_PEMFILE} -o "StrictHostKeyChecking=no" ${CUST_USR}@${targetIp} -t "
#sudo rm -rf $spath
#sudo cp -rv $tmppath $spath
#sudo chown root.root $spath
#sudo rm -rfv $tmppath
#sudo rm -rfv $tmppath/*.old
#sudo rm -rfv $tmppath/*.ovpn
#"
#
#ssh -i ${CUST_PEMFILE} ${CUST_USR}@${targetIp} -t "\
#sudo service openvpn start
#sudo service openvpn status
## sudo cat /var/log/openvpn-status.log
#"
