---
- name: Create local directory
  file:
    path: "{{ local_ovpn_base }}/server"
    state: directory
  delegate_to: localhost

- name: Copy files to local directory
  synchronize:
    src: "{{ ovpn_keys_dir }}/{{ item }}"
    dest: "{{ local_ovpn_base }}/server/{{ item }}"
    mode: pull
  become: true
  with_items:
    - "{{ ovpn_ca_cert_file }}"
    - "{{ ovpn_ca_key_file }}"
    - "{{ ovpn_srv_cert_file }}"
    - "{{ ovpn_srv_key_file }}"
    - "{{ ovpn_dh_file }}"
    - "{{ ovpn_ta_file }}"
