---

- name: Change Key Data
  include_tasks: easy-ovpn-init.yml

- name: push script template
  template: src=../templates/server_gen.sh.j2 dest="/tmp/server_gen.sh"
  become: false

# TODO: Not fully tested

#- name: Enable packet forwarding
#  script: /tmp/eash_opvn_server_gen.sh
#  become: true
#
#- name: Create server key directory
#  file: path="{{ ovpn_keys_dir }}" state=present
#  become: true
#
#- name: copy key files
#  become: true
#  copy: remote_src=true src="{{ easy_ovpn_dir }}/{{ item }}" dest="{{ ovpn_keys_dir }}/{{ item }}"
#  with_items:
#    - "{{ovpn_ca_cert_file}}"
#    - "{{ovpn_ca_key_file}}"
#    - "{{ovpn_srv_cert_file}}"
#    - "{{ovpn_srv_key_file}}"
#    - "{{ovpn_dh_file}}"
#    - "{{ovpn_ta_file}}"
